"""initial migration

Revision ID: 4c40caa1ca45
Revises: 
Create Date: 2023-02-07 16:01:56.506964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c40caa1ca45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hide_posts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hide_posts')
        batch_op.drop_column('hide_email')

    # ### end Alembic commands ###
